
name: owasp_zap_full_scan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Full Scan
        # https://github.com/zaproxy/action-full-scan/commit/6eade0f93b10fad8cfb4e63b979703a2cbd0cc98
        uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98
        with:
          target: "https://qa.orcid.org"
