name: unit_tests_report

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'version tag to use(vx.x.x)'
        required: false
        default: latest
        type: string

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'version tag to use(vx.x.x)'
        required: false
        default: latest
        type: string

jobs:

  tst_hello_world:
    uses: ./.github/workflows/maven_test_report.yml
    with:
      project: hello_world

