name: unit_tests_artifact

# Run tests and upload the results as an artifact
# Can be run from a unprivileged pull_request action
# Reporting is done in the pr_completed.yml workflow

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'Name of the tag to build'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch amount or none'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string
      seed_maven_cache:
        description: Whether to seed cache
        type: boolean
        required: false
        default: true
      install_maven_dependencies:
        description: Whether to install dependencies or use a previous cache
        type: boolean
        required: false
        default: true


  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Name of the tag to build'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch amount or none'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string
      seed_maven_cache:
        description: Whether to seed cache
        type: boolean
        required: false
        default: true
      install_maven_dependencies:
        description: Whether to install dependencies or use a previous cache
        type: boolean
        required: false
        default: true

jobs:
  tst_ml:
    uses: ./.github/workflows/maven_test_artifact.yml
    with:
      project: hello_world
      seed_maven_cache: ${{ inputs.seed_maven_cache }}
      install_maven_dependencies: ${{ inputs.install_maven_dependencies }}


