name: weekly_cache_refresh

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

on:
  schedule:
    - cron: '0 5 * * SUN'

  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test_mvn:
    uses: ./.github/workflows/test_mvn.yml
